import org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeTarget
import org.jetbrains.kotlin.gradle.plugin.mpp.apple.XCFrameworkConfig

apply plugin: 'org.jetbrains.kotlin.multiplatform'
apply plugin: 'maven-publish'

def flopperKitKmp = new XCFrameworkConfig(project, 'FlopperKitKmp')
def appleShimTargets = [
        iosArm64: true,
        iosSimulatorArm64: true,
        iosX64: true,
]

kotlin {
    iosX64()
    iosArm64()
    iosSimulatorArm64()

    targets.withType(KotlinNativeTarget).configureEach {
        if (appleShimTargets.containsKey(it.name)) {
            def capitalizedTarget = it.name.substring(0, 1).toUpperCase() + it.name.substring(1)
            def nativeShimDir = project(':flopper-native').layout.buildDirectory.dir("apple-shim/${it.name}")
            def nativeShimArchive = new File(nativeShimDir.get().asFile, 'libFlopperAppleShim.a')

            it.compilations.main.compileTaskProvider.configure {
                dependsOn(project(':flopper-native').tasks.named("compileFlopperAppleShim${capitalizedTarget}"))
            }

            it.binaries.all { binary ->
                binary.linkerOpts(
                        '-force_load', nativeShimArchive.absolutePath,
                        '-framework', 'Foundation',
                )
            }
        }

        binaries.framework {
            baseName = 'FlopperKitKmp'
            isStatic = true
            export(project(':flopper-native'))
            transitiveExport = true
            freeCompilerArgs += ['-Xbinary=bundleId=com.runspot.flopper.kmp']
            flopperKitKmp.add(it)
        }
    }

    sourceSets {
        commonMain {
            dependencies {
                api project(':flopper-native')
            }
        }
    }
}
