apply plugin: 'com.android.library'
apply plugin: 'org.jetbrains.kotlin.android'
apply plugin: 'com.vanniktech.maven.publish'

android {
    namespace 'com.facebook.flopper.kmp.android'
    compileSdkVersion rootProject.compileSdkVersion
    buildToolsVersion rootProject.buildToolsVersion

    defaultConfig {
        minSdkVersion rootProject.minSdkVersion
        targetSdkVersion rootProject.targetSdkVersion
    }

    compileOptions {
        targetCompatibility rootProject.javaTargetVersion
        sourceCompatibility rootProject.javaTargetVersion
    }

    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    api project(':flopper-core')
    implementation project(':android')
    implementation deps.kotlinStdLibrary
    implementation deps.supportCoreKtx
}
